CREATE DATABASE FIAP;

USE FIAP;

DROP TABLE IF EXISTS TBL_USUARIO;

CREATE  TABLE IF NOT EXISTS TBL_USUARIO (
	LOGIN VARCHAR(60) NOT NULL,
	BLOQUEADO TINYINT(1) NOT NULL,
	GRUPO VARCHAR(60) NOT NULL,
	PERFIL VARCHAR(60) NOT NULL,
	SENHA VARCHAR(60) NOT NULL,
	ULTIMO_ACESSO DATETIME NOT NULL,
	PRIMARY KEY(LOGIN)
)ENGINE = InnoDB;

DROP TABLE IF EXISTS TBL_PRODUTO;

CREATE  TABLE IF NOT EXISTS TBL_PRODUTO (
	CODIGO BIGINT NOT NULL,
	DESCRICAO VARCHAR(60) NOT NULL,
	PRECO DECIMAL(13, 2) NOT NULL,
	ESTOQUE VARCHAR(60) NOT NULL,
	QUANTIDADE_ESTOQUE INT(5) NOT NULL,
	PRIMARY KEY(CODIGO)
)ENGINE = InnoDB;

DROP TABLE IF EXISTS TBL_CLIENTE;

CREATE  TABLE IF NOT EXISTS TBL_CLIENTE (
	LOGIN VARCHAR(60) NOT NULL,
	CODIGO BIGINT(20) NOT NULL,
	NOME VARCHAR(60) NOT NULL,
	ENDERECO VARCHAR(60) NOT NULL,
	TELEFONE INT(14) NOT NULL,
	SITUACAO VARCHAR(60) NOT NULL,
	PRIMARY KEY(LOGIN),
	INDEX FK_CLIENTE_USUARIO (LOGIN ASC),
	CONSTRAINT FK_CLIENTE_USUARIO
		FOREIGN KEY (LOGIN)
		REFERENCES TBL_USUARIO (LOGIN)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;

DROP TABLE IF EXISTS TBL_CLIENTE_FISICO;

CREATE  TABLE IF NOT EXISTS TBL_CLIENTE_FISICO (
	LOGIN VARCHAR(60) NOT NULL,
	RG VARCHAR(20) NOT NULL,
	CPF VARCHAR(20) NOT NULL,
	PRIMARY KEY(LOGIN),
	INDEX FK_CLIENTE_FISICO_CLIENTE (LOGIN ASC),
	CONSTRAINT FK_CLIENTE_FISICO_CLIENTE
		FOREIGN KEY (LOGIN)
		REFERENCES TBL_CLIENTE (LOGIN)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;

DROP TABLE IF EXISTS TBL_CLIENTE_JURIDICO;

CREATE  TABLE IF NOT EXISTS TBL_CLIENTE_JURIDICO (
	LOGIN VARCHAR(60) NOT NULL,
	CNPJ VARCHAR(20) NOT NULL,
	ENDERECO_EMPRESA VARCHAR(60) NOT NULL,
	IE VARCHAR(20) NOT NULL,
	PRIMARY KEY(LOGIN),
	INDEX FK_CLIENTE_JURIDICO_CLIENTE (LOGIN ASC),
	CONSTRAINT FK_CLIENTE_JURIDICO_CLIENTE
		FOREIGN KEY (LOGIN)
		REFERENCES TBL_CLIENTE (LOGIN)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;

DROP TABLE IF EXISTS TBL_RESERVA;

CREATE  TABLE IF NOT EXISTS TBL_RESERVA (
	CODIGO BIGINT(20) NOT NULL,
	DATA DATETIME NOT NULL,
	ATENDENTE VARCHAR(60) NOT NULL,
	SITUACAO VARCHAR(60) NOT NULL,
	VALOR DECIMAL(13, 2) NOT NULL,
	LOGIN_CLIENTE VARCHAR(60) NOT NULL,
	PRIMARY KEY(CODIGO),
	INDEX FK_RESERVA_CLIENTE (LOGIN_CLIENTE ASC),
	CONSTRAINT FK_RESERVA_CLIENTE
		FOREIGN KEY (LOGIN_CLIENTE)
		REFERENCES TBL_CLIENTE (LOGIN)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;

DROP TABLE IF EXISTS TBL_COMPRA;

CREATE  TABLE IF NOT EXISTS TBL_COMPRA (
	NUMERO BIGINT(20) NOT NULL,
	DATA DATETIME NOT NULL,
	SITUACAO VARCHAR(60) NOT NULL,
	VALOR DECIMAL(13, 2) NOT NULL,
	CODIGO_RESERVA BIGINT(20) NOT NULL,
	LOGIN_CLIENTE VARCHAR(60) NOT NULL,
	PRIMARY KEY(NUMERO),
	INDEX FK_COMPRA_RESERVA (CODIGO_RESERVA ASC),
	CONSTRAINT FK_COMPRA_RESERVA
		FOREIGN KEY (CODIGO_RESERVA)
		REFERENCES TBL_RESERVA (CODIGO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	INDEX FK_COMPRA_CLIENTE (LOGIN_CLIENTE ASC),
	CONSTRAINT FK_COMPRA_CLIENTE
		FOREIGN KEY (LOGIN_CLIENTE)
		REFERENCES TBL_CLIENTE (LOGIN)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;

DROP TABLE IF EXISTS TBL_ITEM;

CREATE  TABLE IF NOT EXISTS TBL_ITEM (
	ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	QUANTIDADE INT(5) NOT NULL,
	SITUACAO VARCHAR(60) NOT NULL,
	VALOR DECIMAL(13, 2) NOT NULL,
	CODIGO_RESERVA BIGINT(20) NOT NULL,
	NUMERO_COMPRA BIGINT(20) NOT NULL,
	CODIGO_PRODUTO BIGINT(20) NOT NULL,
	PRIMARY KEY(ID),
	INDEX FK_ITEM_RESERVA (CODIGO_RESERVA ASC),
	CONSTRAINT FK_ITEM_RESERVA
		FOREIGN KEY (CODIGO_RESERVA)
		REFERENCES TBL_RESERVA (CODIGO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	INDEX FK_ITEM_COMPRA (NUMERO_COMPRA ASC),
	CONSTRAINT FK_ITEM_COMPRA
		FOREIGN KEY (NUMERO_COMPRA)
		REFERENCES TBL_COMPRA (NUMERO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	INDEX FK_ITEM_PRODUTO (CODIGO_PRODUTO ASC),
	CONSTRAINT FK_ITEM_PRODUTO
		FOREIGN KEY (CODIGO_PRODUTO)
		REFERENCES TBL_PRODUTO (CODIGO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)ENGINE = InnoDB;